### ISSUE TITLE
解析包异常bug

### ISSUE THREAD

**Issue by Arialena** [4Q-s-r-o/ota_update#67] opened 2021-11-03 09:27 UTC
未知来源安装未开启导致安装异常

**Comment by MartinHlavna** [comment] 2021-11-08 12:35
I am sorry I am not able to understand :) 

Google translating description has given me: "Unknown source installation is not opened, resulting in abnormal installation"

Can you please elaborate in English what the problem is, how are you using plugin and so on?
Flutter doctor, and logcat would also help.

**Comment by ChinaLiJian-Jason** [comment] 2021-11-09 15:47
> 未知来源安装未开启导致安装异常

解决了吗？

**Comment by ChinaLiJian-Jason** [comment] 2021-11-09 15:48
After the download is complete, the installation is not successful, and the error message is displayed: There is a problem parsing the package

**Comment by MartinHlavna** [comment] 2021-11-09 15:52
This usually happens if download crashes for some reason. Android download manager sometimes reports it as download complete even if it is not failed. 

Using sha256checksum to verify integrity of downloaded file usually solves the issue. Also make sure that device has enough free space.

See also issue #56 if it applies to you.

**Comment by MartinHlavna** [comment] 2021-11-09 16:18
Can you provide output from logcat and flutter doctor?

**Comment by ChinaLiJian-Jason** [comment] 2021-11-09 16:27
flutter doctor？Is this information needed? 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0.1 21A559 darwin-arm, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.62.0)
[✓] Connected device (2 available)

**Comment by MartinHlavna** [comment] 2021-11-09 16:36
> It is this information needed?

It is the best way to check for sdk and flutter versions :) 

API level 31 is interesting. Are you using Android 12? It might mean SAF is even more enforced.

**Comment by Arialena** [comment] 2021-11-15 08:21
已解决

**Comment by MartinHlavna** [comment] 2021-11-18 08:04
@ChinaLiJian-Jason can you try to manually delete APK from download folder before executing OtaUpdate? (#56)

**Comment by MartinHlavna** [comment] 2021-11-22 15:56
Should be fixed in 4.0.1

**Closed by MartinHlavna** 2021-11-22 15:56 UTC
Labels: question
