### ISSUE TITLE
OtaStatus.PERMISSION_NOT_GRANTED_ERROR in Android13(compileSdkVersion and targetSdkVersion are both 33)

### ISSUE THREAD

**Issue by hujian-jian** [4Q-s-r-o/ota_update#100] opened 2023-02-16 02:09 UTC
_**When the compileSdkVersion and targetSdkVersion are both 33, running on Android 13 cannot normally request file storage permissions, resulting in failure to update**_

**Comment by MartinHlavna** [comment] 2023-02-16 08:15
Hello,
thanks for the report. This is duplicate of #91 which already has pull request, so fix will be probably published  soon.

**Closed** 2023-02-16 08:16 UTC
Labels: duplicate
