### ISSUE TITLE
I also have this problem.

### ISSUE THREAD

**Issue by mohammadA101** [4Q-s-r-o/ota_update#72] opened 2022-01-26 07:38 UTC
I also have this problem.

but the file name always changes to :
example.apk
example(1).apk
example(2).apk

After the download is complete, when I install it, it says the file is corrupted.
Click the file in the download folder to install it and it will run normally.

what's wrong?

_Originally posted by @JeongEEE in https://github.com/4Q-s-r-o/ota_update/issues/70#issuecomment-1011683572_

**Comment by MartinHlavna** [comment] 2022-02-04 08:44
Hello,

file is renamed by probably by android. But package tries to run installation from the original file. Maybe the app does not have permissions for the file? That would explain renaming and probably installation fail. 

Are you on latest version of ota_update? Starting from 4.0.0 we are saving file to internal app storage instead of Downloads folder to (hopefuly) solve this issue. 

I am closing this issue as duplicate of #70 Please continue discussion there.

**Closed by MartinHlavna** 2022-02-04 08:44 UTC
