### ISSUE TITLE
Installing multiple times fails

### ISSUE THREAD

**Issue by ghost** [4Q-s-r-o/ota_update#25] opened 2020-01-30 18:06 UTC
Hello,

I'm getting a "There was a problem parsing the package." when I attempt to download and install the same package multiple times.  It seems to not download the file, a zero byte file in the downloads folder.

Steps to reproduce:

1. Sideload the app as you see fit.
2. Run the app.
3. Trigger the OTA update and install the app you downloaded.  In my case the exact same apk I originally sideloaded.
4. After it successfully installs trigger the OTA update again.
5. It will instantly fail with the error message "There was a problem parsing the package.".

It feels like the plugin thinks that the file has already been downloaded but it hasn't finished the download.

Any ideas?

Thank you,
Michael

**Comment by MysthawkCanada** [comment] 2020-02-14 17:32
I've updated to version 2.2.1 and the issue seems to have changed, it no longer fails with the error message "There was a problem parsing the package.", instead it gets stuck on the state of "INSTALLING" and doesn't trigger the Android sideloading.

Steps to reproduce:
1. Sideload the app as you see fit.
2. Run the app.
3. Trigger the OTA update and install the app you downloaded. In my case the exact same apk I originally sideloaded.
4. After it successfully installs trigger the OTA update again.
5. This time it will download the file and the last status it will display for me is OtaStatus.INSTALLING.  This is where it would normally trigger the Android install.
6. However, if I close the app now and start at step #2 again, it will install once and then not again.

I seem to have to close the app in between, even though the install of the new app is closing and restarting the app.

I'll keep investigating as time permits.

**Comment by MartinHlavna** [comment] 2020-05-06 15:43
Just curious, what is the use case for this?

**Comment by MysthawkCanada** [comment] 2020-05-06 20:18
I found this when I was testing the OTA updates.  I didn't want to keep changing versions when I wanted to keep modifying my screens and workflow for the OTA updates.  So for me, if I could keep downloading the same file over and over it was faster and easier to work with while still proving that the updates continued to work.

**Comment by MartinHlavna** [comment] 2020-05-07 06:41
Could you try to delete file before downloading and see if problem still persists?

**Comment by MysthawkCanada** [comment] 2020-05-07 12:43
I tried deleting the file before downloading it again and at the time and it didn't help.

**Comment by NoldyNayoan** [comment] 2020-07-30 03:49
Hi, i've tested this plugin and I found that in some device (ex: samsung A10) the downloaded file is appended with sequential number, if I download the file several times (like myapp.apk, myapp 1.apk, myapp 2,apk). So the installation failed, with error 'File Not Found'.  
Also, there is another issue. If I build the apk that is using the plugin, the release.apk cannot be installed (if I use flutter build apk --release). But if I use : flutter build apk --splits-per-abi --release (which produces 3 apks per abi), one of the apk can be installed.
Any thoughts?

**Comment by MartinHlavna** [comment] 2020-07-30 06:45
> Hi, i've tested this plugin and I found that in some device (ex: samsung A10) the downloaded file is appended with sequential number, if I download the file several times (like myapp.apk, myapp 1.apk, myapp 2,apk). So the installation failed, with error 'File Not Found'.

I am afraid we cannot do anything if device download file like this. Maybe forcing unique name via ```destinationFilename``` may solve this for you. 

> Also, there is another issue. If I build the apk that is using the plugin, the release.apk cannot be installed (if I use flutter build apk --release). But if I use : flutter build apk --splits-per-abi --release (which produces 3 apks per abi), one of the apk can be installed.

How did you install app before running update? It may be signature problem - if you installed debug apk via flutter and trying to install  release apk via ota_update this obviously fails. Maybe something similar applies to abi splits? Note that with this plugin you could also use abi spliting but you have to manage a way how to determine which abi download link you pass to ota_update.

**Comment by NoldyNayoan** [comment] 2020-07-30 10:48
> > Hi, i've tested this plugin and I found that in some device (ex: samsung A10) the downloaded file is appended with sequential number, if I download the file several times (like myapp.apk, myapp 1.apk, myapp 2,apk). So the installation failed, with error 'File Not Found'.
> 
> I am afraid we cannot do anything if device download file like this. Maybe forcing unique name via `destinationFilename` may solve this for you.

I have used the 'destinationFilename' but still it renames the downloaded apks with incrementing number. This happens if I integrate the plugin in my app. However strangely enough if I use the example project from github to download the same apk, the downloaded apk is not appended with sequencial number (previous apk is overwitten with the new downloaded apk ) and the apk is successfully installed.

**Comment by MartinHlavna** [comment] 2020-07-30 10:56
Well, dirty workaround would be to add timestamp after apk name in destinationFilename. It is strange indeed we are not experiencing this either in example or our production apps. I understand that DownloadManager renames the file, but we are trying to delete file before initiating download. Maybe it is permissions problem?

**Comment by NoldyNayoan** [comment] 2020-07-30 13:13
I don't think adding timestamp will do good, because I've tried deleting the previous downloaded file first, and the error still appearing. Anyway , I have set the permissions in AndroidManifest.xml (both in main and profile folder) to : 
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />    
    <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" /> 

apk is successfully downloaded (found in Dowload folder), and now there is no File Not Found Error, but suddenly after download my program crash with the following logs/errors in console :

FLUTTER OTA(11772): OTA UPDATE TRACK DOWNLOAD RUNNING
D/FLUTTER OTA(11772): OTA UPDATE SUCCESS

D/AndroidRuntime(11772): Shutting down VM
E/AndroidRuntime(11772): FATAL EXCEPTION: main
E/AndroidRuntime(11772): Process: com.maminoti.pos, PID: 11772
E/AndroidRuntime(11772): java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.DOWNLOAD_COMPLETE flg=0x10 pkg=com.maminoti.pos (has extras) } in com.example.r_upgrade.common.UpgradeManager$3@1e1eec9
E/AndroidRuntime(11772): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1656)
E/AndroidRuntime(11772): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11772): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(11772): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
E/AndroidRuntime(11772): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.Timer.cancel()' on a null object reference
E/AndroidRuntime(11772): 	at com.example.r_upgrade.common.UpgradeManager$3.onReceive(UpgradeManager.java:314)
E/AndroidRuntime(11772): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1646)
E/AndroidRuntime(11772): 	... 8 more
I/Process (11772): Sending signal. PID: 11772 SIG: 9
Lost connection to device.
Exited (sigterm)

**Comment by NoldyNayoan** [comment] 2020-07-30 14:44
Since the download and install functions always work when using the example project, I think the problem is in my project settings. Could be a permission problem like you said. However I've already set (in AndroidManifest.xml):

uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"
uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"
uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES"

Yet, I still get the File not found Error. In console I see :
D/FLUTTER OTA(11772): OTA UPDATE TRACK DOWNLOAD RUNNING
D/FLUTTER OTA(11772): OTA UPDATE SUCCESS

But installation does not continue. I'm truly lost here. Anymore project settings I should be aware of?

**Comment by NoldyNayoan** [comment] 2020-07-31 02:16
Hi, I've found the problem/solution for the File Not Found Error after apk is downloaded on Samsung A10.  Yes, just like you've suspected the error actually comes from Permission for Install from Unknown sources not granted. Somehow the device does not prompt for permission setting even though I have set the REQUEST_INSTALL_PACKAGES in AndroidManifest.xml. 
So I went to device Settings/Applications/myapp  and click myapp icon to show the permissions granted for the app. And there it is, in Advance category : Install From Unknown Sources is not checked. After I checked it and I ran the myapp it download the intended apk and installed it successfully.  
Anyway Thanks for your answers, cause one of them (the permission issue) leads me to  this solution.

**Closed** 2021-03-25 13:17 UTC
Labels: bug
