### ISSUE TITLE
Download progress is negative

### ISSUE THREAD

**Issue by hackgyj** [4Q-s-r-o/ota_update#21] opened 2019-12-30 18:55 UTC
```I/flutter ( 5080): 57
I/flutter ( 5080): 57
I/flutter ( 5080): 57
I/flutter ( 5080): -56
I/flutter ( 5080): -56
I/flutter ( 5080): -54
I/flutter ( 5080): -54
```
After 50% -57%, they all become negative values ​​and decrease.
version：
- ota_update 2.0.2

Hope to fix, thanks for providing!

**Comment by MartinHlavna** [comment] 2020-01-17 08:34
Closing as duplicate of #16

**Closed by MartinHlavna** 2020-01-17 08:34 UTC
Labels: bug, duplicate
