### ISSUE TITLE
I dont know what is it. please fix!

### ISSUE THREAD

**Issue by Nightwelf** [4Q-s-r-o/ota_update#18] opened 2019-10-18 09:18 UTC
Xiaomi Redmi 5 Plus Android 8.1.0

```
Fatal Exception: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
       at android.database.AbstractCursor.checkPosition(AbstractCursor.java:474)
       at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
       at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:74)
       at android.database.CursorWrapper.getLong(CursorWrapper.java:127)
       at android.database.CursorWrapper.getLong(CursorWrapper.java:127)
       at android.app.DownloadManager$CursorTranslator.getLong(DownloadManager.java:1798)
       at android.app.DownloadManager$CursorTranslator.getInt(DownloadManager.java:1788)
       at sk.fourq.otaupdate.OtaUpdatePlugin$3.run(OtaUpdatePlugin.java:34)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by MartinHlavna** [comment] 2019-11-07 08:52
Closing as duplicate of #17

**Closed by MartinHlavna** 2019-11-07 08:52 UTC
