### ISSUE TITLE
 Failed to open event stream

### ISSUE THREAD

**Issue by BedRockGx** [4Q-s-r-o/ota_update#36] opened 2020-07-24 05:28 UTC
This problem occurred when I was using it, and the Android files were all configured. Why? My Flutter version is 1.12+9

E/EventChannel#sk.fourq.ota_update(15952): Failed to open event stream
E/EventChannel#sk.fourq.ota_update(15952): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
E/EventChannel#sk.fourq.ota_update(15952):      at sk.fourq.otaupdate.OtaUpdatePlugin.onListen(OtaUpdatePlugin.java:123)
E/EventChannel#sk.fourq.ota_update(15952):      at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:193)
E/EventChannel#sk.fourq.ota_update(15952):      at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:172)
E/EventChannel#sk.fourq.ota_update(15952):      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/EventChannel#sk.fourq.ota_update(15952):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/EventChannel#sk.fourq.ota_update(15952):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/EventChannel#sk.fourq.ota_update(15952):      at android.os.MessageQueue.next(MessageQueue.java:336)
E/EventChannel#sk.fourq.ota_update(15952):      at android.os.Looper.loop(Looper.java:181)
E/EventChannel#sk.fourq.ota_update(15952):      at android.app.ActivityThread.main(ActivityThread.java:7520)
E/EventChannel#sk.fourq.ota_update(15952):      at java.lang.reflect.Method.invoke(Native Method)
E/EventChannel#sk.fourq.ota_update(15952):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/EventChannel#sk.fourq.ota_update(15952):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
I/flutter (15952): Another exception was thrown: PlatformException(error, Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference, null)

**Comment by BedRockGx** [comment] 2020-07-24 15:06
I can download it, but when parsing the package, tell me:
D/FLUTTER OTA(19526): OTA UPDATE SUCCESS
I/flutter (19526): status:OtaStatus.CHECKSUM_ERROR,value:Checksum verification failed

I think it is caused by the sha256checksum checksum problem. I used sha256 for encryption, but the encrypted key does not match the downloaded file. What happened?

**Comment by MartinHlavna** [comment] 2020-07-29 09:19
Hi! Null pointer is fixed in 2.4.1 just published.

As for the sha256 what have you used to get checksum? Works for me with with checksum generated using linux CLI command ```sha256sum```.

**Comment by MartinHlavna** [comment] 2020-07-29 12:11
Closing as duplicate of #38. If problem with sha256 sum persists feel free to open new issue as this is originally related null pointer

**Closed by MartinHlavna** 2020-07-29 12:11 UTC
Labels: duplicate

**Comment by itMcdull** [comment] 2021-05-14 08:58
> 关闭为[＃38的](https://github.com/4Q-s-r-o/ota_update/issues/38)重复项。如果sha256 sum的问题仍然存在，请随时打开新的问题，因为这最初与null指针有关

The question of consent
`D/FLUTTER OTA(15827): OTA UPDATE ON LISTEN
D/FLUTTER OTA(15827): OTA UPDATE ON STARTING DOWNLOAD
D/FLUTTER OTA(15827): OTA UPDATE DOWNLOAD STARTED 34
D/FLUTTER OTA(15827): OTA UPDATE TRACK DOWNLOAD STARTED 34
D/FLUTTER OTA(15827): OTA UPDATE TRACK DOWNLOAD THREAD STARTED 34
D/FLUTTER OTA(15827): OTA UPDATE PENDING
D/FLUTTER OTA(15827): OTA UPDATE TRACK DOWNLOAD RUNNING 
I/flutter (15827): 0
I/flutter (15827): OtaStatus.DOWNLOADING
D/FLUTTER OTA(15827): OTA UPDATE TRACK DOWNLOAD RUNNING 
I/flutter (15827): 0
I/flutter (15827): OtaStatus.DOWNLOADING
D/FLUTTER OTA(15827): OTA UPDATE TRACK DOWNLOAD RUNNING 
I/flutter (15827): 0
I/flutter (15827): OtaStatus.DOWNLOADING
D/FLUTTER OTA(15827): OTA UPDATE TRACK DOWNLOAD RUNNING 
I/flutter (15827): 0
I/flutter (15827): OtaStatus.DOWNLOADING
D/FLUTTER OTA(15827): OTA UPDATE TRACK DOWNLOAD RUNNING 
I/flutter (15827): 0
I/flutter (15827): OtaStatus.DOWNLOADING
D/FLUTTER OTA(15827): OTA UPDATE TRACK DOWNLOAD RUNNING 
I/flutter (15827): 0
I/flutter (15827): OtaStatus.DOWNLOADING
D/FLUTTER OTA(15827): OTA UPDATE TRACK DOWNLOAD RUNNING 
I/flutter (15827): 0
I/flutter (15827): OtaStatus.DOWNLOADING
D/FLUTTER OTA(15827): OTA UPDATE TRACK DOWNLOAD RUNNING 
I/flutter (15827): 0
I/flutter (15827): OtaStatus.DOWNLOADING
D/FLUTTER OTA(15827): OTA UPDATE TRACK DOWNLOAD RUNNING
I/flutter (15827): 24
I/flutter (15827): OtaStatus.DOWNLOADING
D/FLUTTER OTA(15827): OTA UPDATE TRACK DOWNLOAD RUNNING
I/flutter (15827): 24
I/flutter (15827): OtaStatus.DOWNLOADING
D/FLUTTER OTA(15827): OTA UPDATE TRACK DOWNLOAD RUNNING
I/flutter (15827): 24
I/flutter (15827): OtaStatus.DOWNLOADING
D/FLUTTER OTA(15827): OTA UPDATE TRACK DOWNLOAD RUNNING
I/flutter (15827): 24
I/flutter (15827): OtaStatus.DOWNLOADING
D/FLUTTER OTA(15827): OTA UPDATE TRACK DOWNLOAD RUNNING
I/flutter (15827): 24
I/flutter (15827): OtaStatus.DOWNLOADING
D/FLUTTER OTA(15827): OTA UPDATE TRACK DOWNLOAD RUNNING
I/flutter (15827): 24
I/flutter (15827): OtaStatus.DOWNLOADING
D/FLUTTER OTA(15827): OTA UPDATE TRACK DOWNLOAD RUNNING
I/flutter (15827): 24
I/flutter (15827): OtaStatus.DOWNLOADING
D/FLUTTER OTA(15827): OTA UPDATE TRACK DOWNLOAD RUNNING
I/flutter (15827): 24
I/flutter (15827): OtaStatus.DOWNLOADING
D/FLUTTER OTA(15827): OTA UPDATE TRACK DOWNLOAD RUNNING
I/flutter (15827): 57
I/flutter (15827): OtaStatus.DOWNLOADING
D/FLUTTER OTA(15827): OTA UPDATE TRACK DOWNLOAD RUNNING
I/flutter (15827): 57
I/flutter (15827): OtaStatus.DOWNLOADING
D/FLUTTER OTA(15827): OTA UPDATE TRACK DOWNLOAD RUNNING
I/flutter (15827): 57
I/flutter (15827): OtaStatus.DOWNLOADING
D/FLUTTER OTA(15827): OTA UPDATE TRACK DOWNLOAD RUNNING
I/flutter (15827): 57
I/flutter (15827): OtaStatus.DOWNLOADING
D/FLUTTER OTA(15827): OTA UPDATE TRACK DOWNLOAD RUNNING
I/flutter (15827): 57
I/flutter (15827): OtaStatus.DOWNLOADING
D/FLUTTER OTA(15827): OTA UPDATE TRACK DOWNLOAD RUNNING
I/flutter (15827): 57
I/flutter (15827): OtaStatus.DOWNLOADING
D/FLUTTER OTA(15827): OTA UPDATE TRACK DOWNLOAD RUNNING
I/flutter (15827): 57
I/flutter (15827): OtaStatus.DOWNLOADING
D/FLUTTER OTA(15827): OTA UPDATE TRACK DOWNLOAD RUNNING
I/flutter (15827): 91
I/flutter (15827): OtaStatus.DOWNLOADING
D/FLUTTER OTA(15827): OTA UPDATE TRACK DOWNLOAD RUNNING
I/flutter (15827): 91
I/flutter (15827): OtaStatus.DOWNLOADING
D/FLUTTER OTA(15827): OTA UPDATE SUCCESS
I/flutter (15827): Checksum verification failed
I/flutter (15827): OtaStatus.CHECKSUM_ERROR`
