### ISSUE TITLE
android9 device update failed,automatically quits. but less than android 9 normal.

### ISSUE THREAD

**Issue by littlesalt** [4Q-s-r-o/ota_update#8] opened 2019-03-21 03:49 UTC
The following is the error log:
Launching lib\main.dart on PCT AL10 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Syncing files to device PCT AL10...
I/flutter (17644): newestVersionName:0.9.98
I/flutter (17644): currentVersionName:0.9.97
I/AwareBitmapCacher(17644): init lrucache size: 2097152 pid=17644
D/ZrHung.AppEyeUiProbe(17644): stop checker.
D/ZrHung.AppEyeUiProbe(17644): Current Activity:false
D/ZrHung.AppEyeUiProbe(17644): not watching, wait.
I/flutter (17644): OTA status: OtaStatus.DOWNLOADING : 0 
I/qianxinanmobil(17644): Starting profile saver IsSaveProfileNow end.
I/flutter (17644): OTA status: OtaStatus.INSTALLING :  
W/libEGL  (17644): EGLNativeWindowType 0x71ee981010 disconnect failed
I/SurfaceView(17644): delay destroy surface control
W/libEGL  (17644): EGLNativeWindowType 0x71f87fd010 disconnect failed
I/SurfaceView(17644): need destroy surface control
D/ViewRootImpl[MainActivity](17644): surface should not be released
D/ZrHung.AppEyeUiProbe(17644): notify runnable to start.
D/ZrHung.AppEyeUiProbe(17644): restart watching
D/ZrHung.AppEyeUiProbe(17644): notify runnable to start.
D/ZrHung.AppEyeUiProbe(17644): stop checker.
D/ActivityThread(17644): Remove activity client record, r= ActivityRecord{3e9c0bd token=android.os.BinderProxy@c41d34e {com.longruan.qianxinanmobile/com.longruan.qianxinanmobile.MainActivity}} token= android.os.BinderProxy@c41d34e
D/AndroidRuntime(17644): Shutting down VM
E/AndroidRuntime(17644): FATAL EXCEPTION: main
E/AndroidRuntime(17644): Process: com.longruan.qianxinanmobile, PID: 17644
E/AndroidRuntime(17644): java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.app.FlutterPluginRegistry io.flutter.view.FlutterNativeView.getPluginRegistry()' on a null object reference
E/AndroidRuntime(17644): 	at io.flutter.view.FlutterView.getPluginRegistry(FlutterView.java:219)
E/AndroidRuntime(17644): 	at io.flutter.view.FlutterView.onDetachedFromWindow(FlutterView.java:685)
E/AndroidRuntime(17644): 	at android.view.View.dispatchDetachedFromWindow(View.java:18592)
E/AndroidRuntime(17644): 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3817)
E/AndroidRuntime(17644): 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3817)
E/AndroidRuntime(17644): 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3817)
E/AndroidRuntime(17644): 	at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:4089)
E/AndroidRuntime(17644): 	at android.view.ViewRootImpl.doDie(ViewRootImpl.java:7427)
E/AndroidRuntime(17644): 	at android.view.ViewRootImpl.die(ViewRootImpl.java:7387)
E/AndroidRuntime(17644): 	at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:521)
E/AndroidRuntime(17644): 	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:452)
E/AndroidRuntime(17644): 	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:208)
E/AndroidRuntime(17644): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5141)
E/AndroidRuntime(17644): 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39)
E/AndroidRuntime(17644): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
E/AndroidRuntime(17644): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
E/AndroidRuntime(17644): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2155)
E/AndroidRuntime(17644): 	at android.os.Handler.dispatchMessage(Handler.java:109)
E/AndroidRuntime(17644): 	at android.os.Looper.loop(Looper.java:207)
E/AndroidRuntime(17644): 	at android.app.ActivityThread.main(ActivityThread.java:7539)
E/AndroidRuntime(17644): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17644): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/AndroidRuntime(17644): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
I/Process (17644): Sending signal. PID: 17644 SIG: 9
Lost connection to device.

**Comment by littlesalt** [comment] 2019-03-24 06:31
@ethael @MartinHlavna @tchunwei 
The project is using this feature, please give a solution as soon as possible,thanks!

**Comment by littlesalt** [comment] 2019-03-26 03:24
My download address is based on the HTTP protocol.When I changed to HTTPS, the problem was solved.
Is it that the android9 security level has improved?

**Comment by ethael** [comment] 2019-03-26 06:16
not sure. closing as the problem is not related to this plugin.

**Closed by ethael** 2019-03-26 06:16 UTC
Labels: bug
